apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app
  namespace: bookapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
      - name: book-app
        image: jovanoskajovana/book-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: bookapp-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: bookapp-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookapp-secrets
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: bookapp-config
              key: SPRING_JPA_HIBERNATE_DDL_AUTO
