apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: bookapp-namespace
spec:
  serviceName: postgres-db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: book-store
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: bookapp-config
              key: SPRING_DATASOURCE_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookapp-secrets
              key: SPRING_DATASOURCE_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
      namespace: bookapp-namespace
    spec:
      storageClassName: local-path
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
